export type WebrtcCountryOption = {
  name: string;
  dialCode: string;
  code: string;
  flag: string;
};

export const defaultCountry: WebrtcCountryOption = {
  code: "(GL)",
  flag: "https://cdnjs.cloudflare.com/ajax/libs/twemoji/14.0.2/svg/1f310.svg",
  name: "Global",
  dialCode: "",
};

export const webrtcCountries: WebrtcCountryOption[] = [
  {
    code: "(EG)",
    flag: "https://cdn.jsdelivr.net/gh/lipis/flag-icons/flags/4x3/eg.svg",
    name: "Egypt",
    dialCode: "+20",
  },
  {
    code: "(KSA)",
    flag: "https://cdn.jsdelivr.net/gh/lipis/flag-icons/flags/4x3/sa.svg",
    name: "Saudi Arabia",
    dialCode: "+966",
  },
  {
    code: "(UAE)",
    flag: "https://cdn.jsdelivr.net/gh/lipis/flag-icons/flags/4x3/ae.svg",
    name: "United Arab Emirates",
    dialCode: "+971",
  },
  {
    code: "(QA)",
    flag: "https://cdn.jsdelivr.net/gh/lipis/flag-icons/flags/4x3/qa.svg",
    name: "Qatar",
    dialCode: "+974",
  },
  {
    code: "(KW)",
    flag: "https://cdn.jsdelivr.net/gh/lipis/flag-icons/flags/4x3/kw.svg",
    name: "Kuwait",
    dialCode: "+965",
  },
  {
    code: "(BH)",
    flag: "https://cdn.jsdelivr.net/gh/lipis/flag-icons/flags/4x3/bh.svg",
    name: "Bahrain",
    dialCode: "+973",
  },
  {
    code: "(JO)",
    flag: "https://cdn.jsdelivr.net/gh/lipis/flag-icons/flags/4x3/jo.svg",
    name: "Jordan",
    dialCode: "+962",
  },
  {
    code: "(OM)",
    flag: "https://cdn.jsdelivr.net/gh/lipis/flag-icons/flags/4x3/om.svg",
    name: "Oman",
    dialCode: "+968",
  },
  {
    code: "(IQ)",
    flag: "https://cdn.jsdelivr.net/gh/lipis/flag-icons/flags/4x3/iq.svg",
    name: "Iraq",
    dialCode: "+964",
  },
  defaultCountry,
];

export type CountryOption = {
  label: string;
  value: string;
  code: string;
  flag: string;
};

export const countries: CountryOption[] = [
  {
    label: "Afghanistan",
    value: "Afghanistan",
    code: "AF",
    flag: "🇦🇫",
  },
  {
    label: "land Islands",
    value: "land Islands",
    code: "AX",
    flag: "🇦🇽",
  },
  {
    label: "Albania",
    value: "Albania",
    code: "AL",
    flag: "🇦🇱",
  },
  {
    label: "Algeria",
    value: "Algeria",
    code: "DZ",
    flag: "🇩🇿",
  },
  {
    label: "American Samoa",
    value: "American Samoa",
    code: "AS",
    flag: "🇦🇸",
  },
  {
    label: "AndorrA",
    value: "AndorrA",
    code: "AD",
    flag: "🇦🇩",
  },
  {
    label: "Angola",
    value: "Angola",
    code: "AO",
    flag: "🇦🇴",
  },
  {
    label: "Anguilla",
    value: "Anguilla",
    code: "AI",
    flag: "🇦🇮",
  },
  {
    label: "Antarctica",
    value: "Antarctica",
    code: "AQ",
    flag: "🇦🇶",
  },
  {
    label: "Antigua and Barbuda",
    value: "Antigua and Barbuda",
    code: "AG",
    flag: "🇦🇬",
  },
  {
    label: "Argentina",
    value: "Argentina",
    code: "AR",
    flag: "🇦🇷",
  },
  {
    label: "Armenia",
    value: "Armenia",
    code: "AM",
    flag: "🇦🇲",
  },
  {
    label: "Aruba",
    value: "Aruba",
    code: "AW",
    flag: "🇦🇼",
  },
  {
    label: "Australia",
    value: "Australia",
    code: "AU",
    flag: "🇦🇺",
  },
  {
    label: "Austria",
    value: "Austria",
    code: "AT",
    flag: "🇦🇹",
  },
  {
    label: "Azerbaijan",
    value: "Azerbaijan",
    code: "AZ",
    flag: "🇦🇿",
  },
  {
    label: "Bahamas",
    value: "Bahamas",
    code: "BS",
    flag: "🇧🇸",
  },
  {
    label: "Bahrain",
    value: "Bahrain",
    code: "BH",
    flag: "🇧🇭",
  },
  {
    label: "Bangladesh",
    value: "Bangladesh",
    code: "BD",
    flag: "🇧🇩",
  },
  {
    label: "Barbados",
    value: "Barbados",
    code: "BB",
    flag: "🇧🇧",
  },
  {
    label: "Belarus",
    value: "Belarus",
    code: "BY",
    flag: "🇧🇾",
  },
  {
    label: "Belgium",
    value: "Belgium",
    code: "BE",
    flag: "🇧🇪",
  },
  {
    label: "Belize",
    value: "Belize",
    code: "BZ",
    flag: "🇧🇿",
  },
  {
    label: "Benin",
    value: "Benin",
    code: "BJ",
    flag: "🇧🇯",
  },
  {
    label: "Bermuda",
    value: "Bermuda",
    code: "BM",
    flag: "🇧🇲",
  },
  {
    label: "Bhutan",
    value: "Bhutan",
    code: "BT",
    flag: "🇧🇹",
  },
  {
    label: "Bolivia",
    value: "Bolivia",
    code: "BO",
    flag: "🇧🇴",
  },
  {
    label: "Bosnia and Herzegovina",
    value: "Bosnia and Herzegovina",
    code: "BA",
    flag: "🇧🇦",
  },
  {
    label: "Botswana",
    value: "Botswana",
    code: "BW",
    flag: "🇧🇼",
  },
  {
    label: "Bouvet Island",
    value: "Bouvet Island",
    code: "BV",
    flag: "🇧🇻",
  },
  {
    label: "Brazil",
    value: "Brazil",
    code: "BR",
    flag: "🇧🇷",
  },
  {
    label: "British Indian Ocean Territory",
    value: "British Indian Ocean Territory",
    code: "IO",
    flag: "🇮🇴",
  },
  {
    label: "Brunei Darussalam",
    value: "Brunei Darussalam",
    code: "BN",
    flag: "🇧🇳",
  },
  {
    label: "Bulgaria",
    value: "Bulgaria",
    code: "BG",
    flag: "🇧🇬",
  },
  {
    label: "Burkina Faso",
    value: "Burkina Faso",
    code: "BF",
    flag: "🇧🇫",
  },
  {
    label: "Burundi",
    value: "Burundi",
    code: "BI",
    flag: "🇧🇮",
  },
  {
    label: "Cambodia",
    value: "Cambodia",
    code: "KH",
    flag: "🇰🇭",
  },
  {
    label: "Cameroon",
    value: "Cameroon",
    code: "CM",
    flag: "🇨🇲",
  },
  {
    label: "Canada",
    value: "Canada",
    code: "CA",
    flag: "🇨🇦",
  },
  {
    label: "Cape Verde",
    value: "Cape Verde",
    code: "CV",
    flag: "🇨🇻",
  },
  {
    label: "Cayman Islands",
    value: "Cayman Islands",
    code: "KY",
    flag: "🇰🇾",
  },
  {
    label: "Central African Republic",
    value: "Central African Republic",
    code: "CF",
    flag: "🇨🇫",
  },
  {
    label: "Chad",
    value: "Chad",
    code: "TD",
    flag: "🇹🇩",
  },
  {
    label: "Chile",
    value: "Chile",
    code: "CL",
    flag: "🇨🇱",
  },
  {
    label: "China",
    value: "China",
    code: "CN",
    flag: "🇨🇳",
  },
  {
    label: "Christmas Island",
    value: "Christmas Island",
    code: "CX",
    flag: "🇨🇽",
  },
  {
    label: "Cocos (Keeling) Islands",
    value: "Cocos (Keeling) Islands",
    code: "CC",
    flag: "🇨🇨",
  },
  {
    label: "Colombia",
    value: "Colombia",
    code: "CO",
    flag: "🇨🇴",
  },
  {
    label: "Comoros",
    value: "Comoros",
    code: "KM",
    flag: "🇰🇲",
  },
  {
    label: "Congo",
    value: "Congo",
    code: "CG",
    flag: "🇨🇬",
  },
  {
    label: "Congo, The Democratic Republic of the",
    value: "Congo, The Democratic Republic of the",
    code: "CD",
    flag: "🇨🇩",
  },
  {
    label: "Cook Islands",
    value: "Cook Islands",
    code: "CK",
    flag: "🇨🇰",
  },
  {
    label: "Costa Rica",
    value: "Costa Rica",
    code: "CR",
    flag: "🇨🇷",
  },
  {
    label: "Cote DIvoire",
    value: "Cote DIvoire",
    code: "CI",
    flag: "🇨🇮",
  },
  {
    label: "Croatia",
    value: "Croatia",
    code: "HR",
    flag: "🇭🇷",
  },
  {
    label: "Cuba",
    value: "Cuba",
    code: "CU",
    flag: "🇨🇺",
  },
  {
    label: "Cyprus",
    value: "Cyprus",
    code: "CY",
    flag: "🇨🇾",
  },
  {
    label: "Czech Republic",
    value: "Czech Republic",
    code: "CZ",
    flag: "🇨🇿",
  },
  {
    label: "Denmark",
    value: "Denmark",
    code: "DK",
    flag: "🇩🇰",
  },
  {
    label: "Djibouti",
    value: "Djibouti",
    code: "DJ",
    flag: "🇩🇯",
  },
  {
    label: "Dominica",
    value: "Dominica",
    code: "DM",
    flag: "🇩🇲",
  },
  {
    label: "Dominican Republic",
    value: "Dominican Republic",
    code: "DO",
    flag: "🇩🇴",
  },
  {
    label: "Ecuador",
    value: "Ecuador",
    code: "EC",
    flag: "🇪🇨",
  },
  {
    label: "Egypt",
    value: "Egypt",
    code: "EG",
    flag: "🇪🇬",
  },
  {
    label: "El Salvador",
    value: "El Salvador",
    code: "SV",
    flag: "🇸🇻",
  },
  {
    label: "Equatorial Guinea",
    value: "Equatorial Guinea",
    code: "GQ",
    flag: "🇬🇶",
  },
  {
    label: "Eritrea",
    value: "Eritrea",
    code: "ER",
    flag: "🇪🇷",
  },
  {
    label: "Estonia",
    value: "Estonia",
    code: "EE",
    flag: "🇪🇪",
  },
  {
    label: "Ethiopia",
    value: "Ethiopia",
    code: "ET",
    flag: "🇪🇹",
  },
  {
    label: "Falkland Islands (Malvinas)",
    value: "Falkland Islands (Malvinas)",
    code: "FK",
    flag: "🇫🇰",
  },
  {
    label: "Faroe Islands",
    value: "Faroe Islands",
    code: "FO",
    flag: "🇫🇴",
  },
  {
    label: "Fiji",
    value: "Fiji",
    code: "FJ",
    flag: "🇫🇯",
  },
  {
    label: "Finland",
    value: "Finland",
    code: "FI",
    flag: "🇫🇮",
  },
  {
    label: "France",
    value: "France",
    code: "FR",
    flag: "🇫🇷",
  },
  {
    label: "French Guiana",
    value: "French Guiana",
    code: "GF",
    flag: "🇬🇫",
  },
  {
    label: "French Polynesia",
    value: "French Polynesia",
    code: "PF",
    flag: "🇵🇫",
  },
  {
    label: "French Southern Territories",
    value: "French Southern Territories",
    code: "TF",
    flag: "🇹🇫",
  },
  {
    label: "Gabon",
    value: "Gabon",
    code: "GA",
    flag: "🇬🇦",
  },
  {
    label: "Gambia",
    value: "Gambia",
    code: "GM",
    flag: "🇬🇲",
  },
  {
    label: "Georgia",
    value: "Georgia",
    code: "GE",
    flag: "🇬🇪",
  },
  {
    label: "Germany",
    value: "Germany",
    code: "DE",
    flag: "🇩🇪",
  },
  {
    label: "Ghana",
    value: "Ghana",
    code: "GH",
    flag: "🇬🇭",
  },
  {
    label: "Gibraltar",
    value: "Gibraltar",
    code: "GI",
    flag: "🇬🇮",
  },
  {
    label: "Greece",
    value: "Greece",
    code: "GR",
    flag: "🇬🇷",
  },
  {
    label: "Greenland",
    value: "Greenland",
    code: "GL",
    flag: "🇬🇱",
  },
  {
    label: "Grenada",
    value: "Grenada",
    code: "GD",
    flag: "🇬🇩",
  },
  {
    label: "Guadeloupe",
    value: "Guadeloupe",
    code: "GP",
    flag: "🇬🇵",
  },
  {
    label: "Guam",
    value: "Guam",
    code: "GU",
    flag: "🇬🇺",
  },
  {
    label: "Guatemala",
    value: "Guatemala",
    code: "GT",
    flag: "🇬🇹",
  },
  {
    label: "Guernsey",
    value: "Guernsey",
    code: "GG",
    flag: "🇬🇬",
  },
  {
    label: "Guinea",
    value: "Guinea",
    code: "GN",
    flag: "🇬🇳",
  },
  {
    label: "Guinea-Bissau",
    value: "Guinea-Bissau",
    code: "GW",
    flag: "🇬🇼",
  },
  {
    label: "Guyana",
    value: "Guyana",
    code: "GY",
    flag: "🇬🇾",
  },
  {
    label: "Haiti",
    value: "Haiti",
    code: "HT",
    flag: "🇭🇹",
  },
  {
    label: "Heard Island and Mcdonald Islands",
    value: "Heard Island and Mcdonald Islands",
    code: "HM",
    flag: "🇭🇲",
  },
  {
    label: "Holy See (Vatican City State)",
    value: "Holy See (Vatican City State)",
    code: "VA",
    flag: "🇻🇦",
  },
  {
    label: "Honduras",
    value: "Honduras",
    code: "HN",
    flag: "🇭🇳",
  },
  {
    label: "Hong Kong",
    value: "Hong Kong",
    code: "HK",
    flag: "🇭🇰",
  },
  {
    label: "Hungary",
    value: "Hungary",
    code: "HU",
    flag: "🇭🇺",
  },
  {
    label: "Iceland",
    value: "Iceland",
    code: "IS",
    flag: "🇮🇸",
  },
  {
    label: "India",
    value: "India",
    code: "IN",
    flag: "🇮🇳",
  },
  {
    label: "Indonesia",
    value: "Indonesia",
    code: "ID",
    flag: "🇮🇩",
  },
  {
    label: "Iran, Islamic Republic Of",
    value: "Iran, Islamic Republic Of",
    code: "IR",
    flag: "🇮🇷",
  },
  {
    label: "Iraq",
    value: "Iraq",
    code: "IQ",
    flag: "🇮🇶",
  },
  {
    label: "Ireland",
    value: "Ireland",
    code: "IE",
    flag: "🇮🇪",
  },
  {
    label: "Isle of Man",
    value: "Isle of Man",
    code: "IM",
    flag: "🇮🇲",
  },
  {
    label: "Israel",
    value: "Israel",
    code: "IL",
    flag: "🇮🇱",
  },
  {
    label: "Italy",
    value: "Italy",
    code: "IT",
    flag: "🇮🇹",
  },
  {
    label: "Jamaica",
    value: "Jamaica",
    code: "JM",
    flag: "🇯🇲",
  },
  {
    label: "Japan",
    value: "Japan",
    code: "JP",
    flag: "🇯🇵",
  },
  {
    label: "Jersey",
    value: "Jersey",
    code: "JE",
    flag: "🇯🇪",
  },
  {
    label: "Jordan",
    value: "Jordan",
    code: "JO",
    flag: "🇯🇴",
  },
  {
    label: "Kazakhstan",
    value: "Kazakhstan",
    code: "KZ",
    flag: "🇰🇿",
  },
  {
    label: "Kenya",
    value: "Kenya",
    code: "KE",
    flag: "🇰🇪",
  },
  {
    label: "Kiribati",
    value: "Kiribati",
    code: "KI",
    flag: "🇰🇮",
  },
  {
    label: "Korea, Democratic PeopleS Republic of",
    value: "Korea, Democratic PeopleS Republic of",
    code: "KP",
    flag: "🇰🇵",
  },
  {
    label: "Korea, Republic of",
    value: "Korea, Republic of",
    code: "KR",
    flag: "🇰🇷",
  },
  {
    label: "Kuwait",
    value: "Kuwait",
    code: "KW",
    flag: "🇰🇼",
  },
  {
    label: "Kyrgyzstan",
    value: "Kyrgyzstan",
    code: "KG",
    flag: "🇰🇬",
  },
  {
    label: "Lao PeopleS Democratic Republic",
    value: "Lao PeopleS Democratic Republic",
    code: "LA",
    flag: "🇱🇦",
  },
  {
    label: "Latvia",
    value: "Latvia",
    code: "LV",
    flag: "🇱🇻",
  },
  {
    label: "Lebanon",
    value: "Lebanon",
    code: "LB",
    flag: "🇱🇧",
  },
  {
    label: "Lesotho",
    value: "Lesotho",
    code: "LS",
    flag: "🇱🇸",
  },
  {
    label: "Liberia",
    value: "Liberia",
    code: "LR",
    flag: "🇱🇷",
  },
  {
    label: "Libyan Arab Jamahiriya",
    value: "Libyan Arab Jamahiriya",
    code: "LY",
    flag: "🇱🇾",
  },
  {
    label: "Liechtenstein",
    value: "Liechtenstein",
    code: "LI",
    flag: "🇱🇮",
  },
  {
    label: "Lithuania",
    value: "Lithuania",
    code: "LT",
    flag: "🇱🇹",
  },
  {
    label: "Luxembourg",
    value: "Luxembourg",
    code: "LU",
    flag: "🇱🇺",
  },
  {
    label: "Macao",
    value: "Macao",
    code: "MO",
    flag: "🇲🇴",
  },
  {
    label: "Macedonia, The Former Yugoslav Republic of",
    value: "Macedonia, The Former Yugoslav Republic of",
    code: "MK",
    flag: "🇲🇰",
  },
  {
    label: "Madagascar",
    value: "Madagascar",
    code: "MG",
    flag: "🇲🇬",
  },
  {
    label: "Malawi",
    value: "Malawi",
    code: "MW",
    flag: "🇲🇼",
  },
  {
    label: "Malaysia",
    value: "Malaysia",
    code: "MY",
    flag: "🇲🇾",
  },
  {
    label: "Maldives",
    value: "Maldives",
    code: "MV",
    flag: "🇲🇻",
  },
  {
    label: "Mali",
    value: "Mali",
    code: "ML",
    flag: "🇲🇱",
  },
  {
    label: "Malta",
    value: "Malta",
    code: "MT",
    flag: "🇲🇹",
  },
  {
    label: "Marshall Islands",
    value: "Marshall Islands",
    code: "MH",
    flag: "🇲🇭",
  },
  {
    label: "Martinique",
    value: "Martinique",
    code: "MQ",
    flag: "🇲🇶",
  },
  {
    label: "Mauritania",
    value: "Mauritania",
    code: "MR",
    flag: "🇲🇷",
  },
  {
    label: "Mauritius",
    value: "Mauritius",
    code: "MU",
    flag: "🇲🇺",
  },
  {
    label: "Mayotte",
    value: "Mayotte",
    code: "YT",
    flag: "🇾🇹",
  },
  {
    label: "Mexico",
    value: "Mexico",
    code: "MX",
    flag: "🇲🇽",
  },
  {
    label: "Micronesia, Federated States of",
    value: "Micronesia, Federated States of",
    code: "FM",
    flag: "🇫🇲",
  },
  {
    label: "Moldova, Republic of",
    value: "Moldova, Republic of",
    code: "MD",
    flag: "🇲🇩",
  },
  {
    label: "Monaco",
    value: "Monaco",
    code: "MC",
    flag: "🇲🇨",
  },
  {
    label: "Mongolia",
    value: "Mongolia",
    code: "MN",
    flag: "🇲🇳",
  },
  {
    label: "Montenegro",
    value: "Montenegro",
    code: "ME",
    flag: "🇲🇪",
  },
  {
    label: "Montserrat",
    value: "Montserrat",
    code: "MS",
    flag: "🇲🇸",
  },
  {
    label: "Morocco",
    value: "Morocco",
    code: "MA",
    flag: "🇲🇦",
  },
  {
    label: "Mozambique",
    value: "Mozambique",
    code: "MZ",
    flag: "🇲🇿",
  },
  {
    label: "Myanmar",
    value: "Myanmar",
    code: "MM",
    flag: "🇲🇲",
  },
  {
    label: "Namibia",
    value: "Namibia",
    code: "NA",
    flag: "🇳🇦",
  },
  {
    label: "Nauru",
    value: "Nauru",
    code: "NR",
    flag: "🇳🇷",
  },
  {
    label: "Nepal",
    value: "Nepal",
    code: "NP",
    flag: "🇳🇵",
  },
  {
    label: "Netherlands",
    value: "Netherlands",
    code: "NL",
    flag: "🇳🇱",
  },
  {
    label: "Netherlands Antilles",
    value: "Netherlands Antilles",
    code: "AN",
    flag: "🇦🇳",
  },
  {
    label: "New Caledonia",
    value: "New Caledonia",
    code: "NC",
    flag: "🇳🇨",
  },
  {
    label: "New Zealand",
    value: "New Zealand",
    code: "NZ",
    flag: "🇳🇿",
  },
  {
    label: "Nicaragua",
    value: "Nicaragua",
    code: "NI",
    flag: "🇳🇮",
  },
  {
    label: "Niger",
    value: "Niger",
    code: "NE",
    flag: "🇳🇪",
  },
  {
    label: "Nigeria",
    value: "Nigeria",
    code: "NG",
    flag: "🇳🇬",
  },
  {
    label: "Niue",
    value: "Niue",
    code: "NU",
    flag: "🇳🇺",
  },
  {
    label: "Norfolk Island",
    value: "Norfolk Island",
    code: "NF",
    flag: "🇳🇫",
  },
  {
    label: "Northern Mariana Islands",
    value: "Northern Mariana Islands",
    code: "MP",
    flag: "🇲🇵",
  },
  {
    label: "Norway",
    value: "Norway",
    code: "NO",
    flag: "🇳🇴",
  },
  {
    label: "Oman",
    value: "Oman",
    code: "OM",
    flag: "🇴🇲",
  },
  {
    label: "Pakistan",
    value: "Pakistan",
    code: "PK",
    flag: "🇵🇰",
  },
  {
    label: "Palau",
    value: "Palau",
    code: "PW",
    flag: "🇵🇼",
  },
  {
    label: "Palestinian Territory, Occupied",
    value: "Palestinian Territory, Occupied",
    code: "PS",
    flag: "🇵🇸",
  },
  {
    label: "Panama",
    value: "Panama",
    code: "PA",
    flag: "🇵🇦",
  },
  {
    label: "Papua New Guinea",
    value: "Papua New Guinea",
    code: "PG",
    flag: "🇵🇬",
  },
  {
    label: "Paraguay",
    value: "Paraguay",
    code: "PY",
    flag: "🇵🇾",
  },
  {
    label: "Peru",
    value: "Peru",
    code: "PE",
    flag: "🇵🇪",
  },
  {
    label: "Philippines",
    value: "Philippines",
    code: "PH",
    flag: "🇵🇭",
  },
  {
    label: "Pitcairn",
    value: "Pitcairn",
    code: "PN",
    flag: "🇵🇳",
  },
  {
    label: "Poland",
    value: "Poland",
    code: "PL",
    flag: "🇵🇱",
  },
  {
    label: "Portugal",
    value: "Portugal",
    code: "PT",
    flag: "🇵🇹",
  },
  {
    label: "Puerto Rico",
    value: "Puerto Rico",
    code: "PR",
    flag: "🇵🇷",
  },
  {
    label: "Qatar",
    value: "Qatar",
    code: "QA",
    flag: "🇶🇦",
  },
  {
    label: "Reunion",
    value: "Reunion",
    code: "RE",
    flag: "🇷🇪",
  },
  {
    label: "Romania",
    value: "Romania",
    code: "RO",
    flag: "🇷🇴",
  },
  {
    label: "Russian Federation",
    value: "Russian Federation",
    code: "RU",
    flag: "🇷🇺",
  },
  {
    label: "RWANDA",
    value: "RWANDA",
    code: "RW",
    flag: "🇷🇼",
  },
  {
    label: "Saint Helena",
    value: "Saint Helena",
    code: "SH",
    flag: "🇸🇭",
  },
  {
    label: "Saint Kitts and Nevis",
    value: "Saint Kitts and Nevis",
    code: "KN",
    flag: "🇰🇳",
  },
  {
    label: "Saint Lucia",
    value: "Saint Lucia",
    code: "LC",
    flag: "🇱🇨",
  },
  {
    label: "Saint Pierre and Miquelon",
    value: "Saint Pierre and Miquelon",
    code: "PM",
    flag: "🇵🇲",
  },
  {
    label: "Saint Vincent and the Grenadines",
    value: "Saint Vincent and the Grenadines",
    code: "VC",
    flag: "🇻🇨",
  },
  {
    label: "Samoa",
    value: "Samoa",
    code: "WS",
    flag: "🇼🇸",
  },
  {
    label: "San Marino",
    value: "San Marino",
    code: "SM",
    flag: "🇸🇲",
  },
  {
    label: "Sao Tome and Principe",
    value: "Sao Tome and Principe",
    code: "ST",
    flag: "🇸🇹",
  },
  {
    label: "Saudi Arabia",
    value: "Saudi Arabia",
    code: "SA",
    flag: "🇸🇦",
  },
  {
    label: "Senegal",
    value: "Senegal",
    code: "SN",
    flag: "🇸🇳",
  },
  {
    label: "Serbia",
    value: "Serbia",
    code: "RS",
    flag: "🇷🇸",
  },
  {
    label: "Seychelles",
    value: "Seychelles",
    code: "SC",
    flag: "🇸🇨",
  },
  {
    label: "Sierra Leone",
    value: "Sierra Leone",
    code: "SL",
    flag: "🇸🇱",
  },
  {
    label: "Singapore",
    value: "Singapore",
    code: "SG",
    flag: "🇸🇬",
  },
  {
    label: "Slovakia",
    value: "Slovakia",
    code: "SK",
    flag: "🇸🇰",
  },
  {
    label: "Slovenia",
    value: "Slovenia",
    code: "SI",
    flag: "🇸🇮",
  },
  {
    label: "Solomon Islands",
    value: "Solomon Islands",
    code: "SB",
    flag: "🇸🇧",
  },
  {
    label: "Somalia",
    value: "Somalia",
    code: "SO",
    flag: "🇸🇴",
  },
  {
    label: "South Africa",
    value: "South Africa",
    code: "ZA",
    flag: "🇿🇦",
  },
  {
    label: "South Georgia and the South Sandwich Islands",
    value: "South Georgia and the South Sandwich Islands",
    code: "GS",
    flag: "🇬🇸",
  },
  {
    label: "Spain",
    value: "Spain",
    code: "ES",
    flag: "🇪🇸",
  },
  {
    label: "Sri Lanka",
    value: "Sri Lanka",
    code: "LK",
    flag: "🇱🇰",
  },
  {
    label: "Sudan",
    value: "Sudan",
    code: "SD",
    flag: "🇸🇩",
  },
  {
    label: "Surilabel",
    value: "Surilabel",
    code: "SR",
    flag: "🇸🇷",
  },
  {
    label: "Svalbard and Jan Mayen",
    value: "Svalbard and Jan Mayen",
    code: "SJ",
    flag: "🇸🇯",
  },
  {
    label: "Swaziland",
    value: "Swaziland",
    code: "SZ",
    flag: "🇸🇿",
  },
  {
    label: "Sweden",
    value: "Sweden",
    code: "SE",
    flag: "🇸🇪",
  },
  {
    label: "Switzerland",
    value: "Switzerland",
    code: "CH",
    flag: "🇨🇭",
  },
  {
    label: "Syrian Arab Republic",
    value: "Syrian Arab Republic",
    code: "SY",
    flag: "🇸🇾",
  },
  {
    label: "Taiwan, Province of China",
    value: "Taiwan, Province of China",
    code: "TW",
    flag: "🇹🇼",
  },
  {
    label: "Tajikistan",
    value: "Tajikistan",
    code: "TJ",
    flag: "🇹🇯",
  },
  {
    label: "Tanzania, United Republic of",
    value: "Tanzania, United Republic of",
    code: "TZ",
    flag: "🇹🇿",
  },
  {
    label: "Thailand",
    value: "Thailand",
    code: "TH",
    flag: "🇹🇭",
  },
  {
    label: "Timor-Leste",
    value: "Timor-Leste",
    code: "TL",
    flag: "🇹🇱",
  },
  {
    label: "Togo",
    value: "Togo",
    code: "TG",
    flag: "🇹🇬",
  },
  {
    label: "Tokelau",
    value: "Tokelau",
    code: "TK",
    flag: "🇹🇰",
  },
  {
    label: "Tonga",
    value: "Tonga",
    code: "TO",
    flag: "🇹🇴",
  },
  {
    label: "Trinidad and Tobago",
    value: "Trinidad and Tobago",
    code: "TT",
    flag: "🇹🇹",
  },
  {
    label: "Tunisia",
    value: "Tunisia",
    code: "TN",
    flag: "🇹🇳",
  },
  {
    label: "Turkey",
    value: "Turkey",
    code: "TR",
    flag: "🇹🇷",
  },
  {
    label: "Turkmenistan",
    value: "Turkmenistan",
    code: "TM",
    flag: "🇹🇲",
  },
  {
    label: "Turks and Caicos Islands",
    value: "Turks and Caicos Islands",
    code: "TC",
    flag: "🇹🇨",
  },
  {
    label: "Tuvalu",
    value: "Tuvalu",
    code: "TV",
    flag: "🇹🇻",
  },
  {
    label: "Uganda",
    value: "Uganda",
    code: "UG",
    flag: "🇺🇬",
  },
  {
    label: "Ukraine",
    value: "Ukraine",
    code: "UA",
    flag: "🇺🇦",
  },
  {
    label: "United Arab Emirates",
    value: "United Arab Emirates",
    code: "AE",
    flag: "🇦🇪",
  },
  {
    label: "United Kingdom",
    value: "United Kingdom",
    code: "GB",
    flag: "🇬🇧",
  },
  {
    label: "United States",
    value: "United States",
    code: "US",
    flag: "🇺🇸",
  },
  {
    label: "United States Minor Outlying Islands",
    value: "United States Minor Outlying Islands",
    code: "UM",
    flag: "🇺🇲",
  },
  {
    label: "Uruguay",
    value: "Uruguay",
    code: "UY",
    flag: "🇺🇾",
  },
  {
    label: "Uzbekistan",
    value: "Uzbekistan",
    code: "UZ",
    flag: "🇺🇿",
  },
  {
    label: "Vanuatu",
    value: "Vanuatu",
    code: "VU",
    flag: "🇻🇺",
  },
  {
    label: "Venezuela",
    value: "Venezuela",
    code: "VE",
    flag: "🇻🇪",
  },
  {
    label: "Viet Nam",
    value: "Viet Nam",
    code: "VN",
    flag: "🇻🇳",
  },
  {
    label: "Virgin Islands, British",
    value: "Virgin Islands, British",
    code: "VG",
    flag: "🇻🇬",
  },
  {
    label: "Virgin Islands, U.S.",
    value: "Virgin Islands, U.S.",
    code: "VI",
    flag: "🇻🇮",
  },
  {
    label: "Wallis and Futuna",
    value: "Wallis and Futuna",
    code: "WF",
    flag: "🇼🇫",
  },
  {
    label: "Western Sahara",
    value: "Western Sahara",
    code: "EH",
    flag: "🇪🇭",
  },
  {
    label: "Yemen",
    value: "Yemen",
    code: "YE",
    flag: "🇾🇪",
  },
  {
    label: "Zambia",
    value: "Zambia",
    code: "ZM",
    flag: "🇿🇲",
  },
  {
    label: "Zimbabwe",
    value: "Zimbabwe",
    code: "ZW",
    flag: "🇿🇼",
  },
];
