import type { Metadata } from "next";
import { PropsWithChildren } from "react";
import { locales, LocaleSlug } from "@/i18n/config";
import localFont from "next/font/local";
import MainProvider from "@/providers/MainProvider";

const geistSans = localFont({
  src: "../fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "../fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type RootLayoutProps = PropsWithChildren<{
  params: Promise<{ locale: LocaleSlug }>;
}>;

const RootLayout = async ({ children, params }: RootLayoutProps) => {
  const { locale } = await params;
  const localeObj = locales[locale];

  return (
    <html lang={locale} dir={localeObj.dir}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <MainProvider>{children}</MainProvider>
      </body>
    </html>
  );
};

export default RootLayout;
